apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: 334372355104.dkr.ecr.eu-west-2.amazonaws.com/springboot-repository:latest
          ports:
            - containerPort: 8080
