name: Springboot-tour

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify

    - name: Test report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: Springboot Report
        path: target/surefire-reports

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        target: murtaza66/springboot-tour:latest
      env:
        DOCKER_USERNAME: murtaza66
        DOCKER_PASSWORD: Murti_666
