name: Springboot-tour

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn clean verify
        JAR_PATH=$(find target -name '*.jar' -type f)
        echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

    - name: Test report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: Springboot Report
        path: target/surefire-reports

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/springboot:latest
        build-args: JAR_PATH=${{ env.JAR_PATH }}

    - name: Deploy To EC2 using Terraform
      run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'bash -s' << 'EOF'
          sudo apt update
          sudo apt install -y unzip
          wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
          unzip terraform_0.15.5_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform init
          terraform apply -auto-approve
          EQF
