name: Terraform Workflow

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0  # Specify your Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Optionally, you can include additional steps like formatting, linting, etc.

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Apply only for main branch pushes
        run: terraform apply tfplan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
